//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityManagementSystemFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignCourse
    {
        public int AssignCourseId { get; set; }
        [Required(ErrorMessage = "You have to select any Department")]
        public int DepartmentId { get; set; }
        [Required(ErrorMessage = "You have to select a Teacher")]
        public int TeacherId { get; set; }
        public double CreditTaken { get; set; }
        public double RemaingCredit { get; set; }
        [Required(ErrorMessage = "You have to select a Course")]
        public int CourseId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Course Course { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
