//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystemFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Day
    {
        public Day()
        {
            this.RoomAllocations = new HashSet<RoomAllocation>();
        }
    
        public int DayId { get; set; }
        public string DayName { get; set; }
    
        public virtual ICollection<RoomAllocation> RoomAllocations { get; set; }
    }
}
