//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace UniversityManagementSystemFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.AssignCourses = new HashSet<AssignCourse>();
            this.Courses = new HashSet<Course>();
            this.RoomAllocations = new HashSet<RoomAllocation>();
            this.Students = new HashSet<Student>();
            this.Teachers = new HashSet<Teacher>();
        }
    
        public int DepartmentId { get; set; }
        [Display(Name = "Department Code")]
        [Required(ErrorMessage = "You have to enter the Department Code.")]
        [StringLength(7, MinimumLength = 2, ErrorMessage = "Department Code Must be 2 to 7 Character long.")]
        [Remote("CheckCode", "Department", HttpMethod = "POST", ErrorMessage = "This Department code Already Exist")]
        public string DepartmentCode { get; set; }
        [Display(Name = "Department Name")]
        [Required(ErrorMessage = "You have to enter the Department Name.")]
        [Remote("CheckName", "Department", HttpMethod = "POST", ErrorMessage = "This Department Name Already Exist")]
        public string DepartmnetName { get; set; }
    
        public virtual ICollection<AssignCourse> AssignCourses { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<RoomAllocation> RoomAllocations { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}
