//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystemFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        public Designation()
        {
            this.Teachers = new HashSet<Teacher>();
        }
    
        public int DesignationId { get; set; }
        public string DesignationName { get; set; }
    
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}
