//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityManagementSystemFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollCourse
    {
        public int EnrollCourseId { get; set; }
        [Required(ErrorMessage = "Please select Registration Id")]
        public int StudentId { get; set; }
        [Required(ErrorMessage = "Please Select a Course")]
        public int CourseId { get; set; }
        [Required(ErrorMessage = "Enroll Date Can't be Empty")]
        [DataType(DataType.Date)]
        public System.DateTime EnrollDate { get; set; }
        public string GradeName { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}
