//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystemFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public Grade()
        {
            this.ResultEntries = new HashSet<ResultEntry>();
        }
    
        public int GradeId { get; set; }
        public string GradeName { get; set; }
    
        public virtual ICollection<ResultEntry> ResultEntries { get; set; }
    }
}
