//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityManagementSystemFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultEntry
    {
        public int ResultEntryId { get; set; }
        [Display(Name = "Student Reg.No")]
        [Required(ErrorMessage = "Please Select Student Registration Id")]
        public int StudentId { get; set; }
        [Display(Name = "Course Name")]
        [Required(ErrorMessage = "Please Select Course Name")]
        public int CourseId { get; set; }
        [Display(Name = "Grade")]
        [Required(ErrorMessage = "You have to enter any Grade")]
        public int GradeId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual Student Student { get; set; }
    }
}
