//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityManagementSystemFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomAllocation
    {
        public int RoomAllocationId { get; set; }
        [Required(ErrorMessage = "Please select a Department")]
        public int DepartmentId { get; set; }
        [Required(ErrorMessage = "Please select a Course")]
        public int CourseId { get; set; }
        [Required(ErrorMessage = "Please select a Room")]
        public int RoomId { get; set; }
        [Required(ErrorMessage = "Please select a Day")]
        public int DayId { get; set; }
        [Required(ErrorMessage = "Please enter time")]
        [DataType(DataType.Time)]
        public string StartTime { get; set; }
        [Required(ErrorMessage = "Please enter time")]
        [DataType(DataType.Time)]
        public string EndTime { get; set; }
        public string RoomStatus { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Day Day { get; set; }
        public virtual Department Department { get; set; }
        public virtual Room Room { get; set; }
    }
}
