//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace UniversityManagementSystemFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.AssignCourses = new HashSet<AssignCourse>();
            this.Courses = new HashSet<Course>();
        }
    
        public int TeacherId { get; set; }
        [Display(Name = "Teacher Name")]
        [Required(ErrorMessage = "You have to enter the Teacher Name.")]
        public string TeacherName { get; set; }
        [Display(Name = "Address")]
        [Required(ErrorMessage = "You have to enter the Address.")]
        public string TeacherAddress { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "You have to enter the Email.")]
        [RegularExpression(@"[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", ErrorMessage = "E-mail is not valid")]
        [Remote("CheckEmail", "Teacher", HttpMethod = "POST", ErrorMessage = "This Email Address Already Registred !")]
        public string TeacherEmail { get; set; }
        [Display(Name = "Contact No")]
        [Required(ErrorMessage = "You have to enter the Contact No.")]
        [RegularExpression(@"^01\d{9}$", ErrorMessage = "Mobile No is not valid")]
        public string TeacherContact { get; set; }
        [Display(Name = "Designation")]
        [Required(ErrorMessage = "You have to select the Designation.")]
        public int DesignationId { get; set; }
        [Display(Name = "Credit To Be Taken")]
        [Required(ErrorMessage = "You have to enter the Credit To Be Taken.")]
        [RegularExpression(@"^\d{1,5}(\.\d{1,3})?$", ErrorMessage = "Credit To Be Taken must have to be Non negative decimal no")]
        public double CraditTaken { get; set; }
        [Display(Name = "Department")]
        [Required(ErrorMessage = "You have to selecct Department.")]
        public int DepartmentId { get; set; }
    
        public virtual ICollection<AssignCourse> AssignCourses { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
    }
}
